### ISSUE TITLE
GET /api/submissions?filter=pending is not working

### ISSUE THREAD

**Issue by obdulia-losantos** [eHealthAfrica/kazana-raw-data#20]
- Request
GET `http://127.0.0.1:5000/kazana/raw-data/api/submissions?filter=pending`

- Response
```json
{
  "statusCode": 400, 
  "error": "Bad Request", 
  "message": "Some query parameter is invalid"
}
```

- kazana version `6.0.0`

**Comment by jo** [comment]
```
 reason: '{include_docs:true} is invalid for reduce' }
```

**Comment by obdulia-losantos** [comment]
Do you mean this?
https://github.com/eHealthAfrica/kazana-raw-data/blob/master/lib/routes/submissions/all.js#L35-L37

```
function findFiltered (store, user, filter) {
  var options = {
    include_docs: true
  }
...
```

**Comment by jo** [comment]
yes, need to add `reduce=false`

**Comment by jo** [comment]
https://github.com/eHealthAfrica/kazana-raw-data/pull/21
